# Generated by Django 5.2.4 on 2026-01-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='carb',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='탄수화물(g)'),
        ),
        migrations.AddField(
            model_name='post',
            name='fat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='지방(g)'),
        ),
        migrations.AddField(
            model_name='post',
            name='ingPhoto',
            field=models.ImageField(blank=True, upload_to='posts/%Y%m%d', verbose_name='영양 성분 이미지'),
        ),
        migrations.AddField(
            model_name='post',
            name='protien',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='단백질(g)'),
        ),
    ]
