# Generated by Django 5.2.4 on 2026-01-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_carb_post_fat_post_ingphoto_post_protien'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='calorie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='칼로리 정보(kcal)'),
        ),
    ]
