# Generated by Django 5.2.9 on 2025-12-31 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_title", models.CharField(max_length=32)),
                ("release_year", models.CharField(max_length=32)),
                ("director_name", models.CharField(max_length=32)),
                ("main_actor", models.CharField(max_length=32)),
                ("genre", models.CharField(max_length=32)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("running_time", models.IntegerField()),
                ("review_content", models.TextField()),
            ],
        ),
    ]
