# Generated by Django 5.2.9 on 2026-01-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                (
                    "image",
                    models.ImageField(
                        default="default.jpg", upload_to="thumbNail_pics"
                    ),
                ),
                ("content", models.TextField()),
                ("interest", models.TextField()),
                (
                    "devtool",
                    models.CharField(
                        choices=[
                            ("django", "장고"),
                            ("react", "리액트"),
                            ("flask", "플라스크"),
                            ("fastApi", "패스트 API"),
                        ],
                        default="django",
                        max_length=10,
                    ),
                ),
                ("interestAmount", models.IntegerField()),
            ],
        ),
    ]
