# Generated by Django 5.2.9 on 2026-01-01 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myIdeas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DevTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="idea",
            name="interest",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="idea",
            name="devtool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myIdeas.devtool"
            ),
        ),
    ]
