# Generated by Django 5.2.9 on 2026-01-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myIdeas", "0002_devtool_alter_idea_interest_alter_idea_devtool"),
    ]

    operations = [
        migrations.AddField(
            model_name="devtool",
            name="explain",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="devtool",
            name="type",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
    ]
