# Generated by Django 5.2.9 on 2026-01-02 07:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myIdeas", "0004_ideastar"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ideastar",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="ideastar",
            name="user",
        ),
    ]
